# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  web:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: .
    env_file:
     - env_vars.env
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:10.3
    env_file:
      - env_vars.env
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:
